# Generated by Django 5.1 on 2024-11-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='servings_per_container',
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='added_sugars',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='calories_from_fat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='chloride',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='chromium',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='copper',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='dietary_fiber',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='folate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='iron',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='magnesium',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='manganese',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='molybdenum',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='monounsaturated_fat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='niacin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='pantothenic_acid',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='phosphorus',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='polyunsaturated_fat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='riboflavin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='saturated_fat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='selenium',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar_alcohol',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugars',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='thiamin',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='total_fat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='trans_fat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_a',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_b12',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_b6',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_c',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_d',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_e',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='vitamin_k',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='zinc',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
    ]
