# Generated by Django 5.1 on 2024-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0002_remove_nutrition_servings_per_container_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='iodine',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
