# Generated by Django 5.1 on 2024-11-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0003_alter_nutrition_iodine'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='salt',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='iodine',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=6, null=True),
        ),
    ]
