# Generated by Django 5.1 on 2024-11-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0005_alter_nutrition_added_sugars_alter_nutrition_biotin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
