# Generated by Django 5.1 on 2024-11-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
        ),
    ]
