# Generated by Django 5.1 on 2024-11-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('risk_level', models.IntegerField(choices=[(0, 'Low Risk'), (1, 'Moderate Risk'), (2, 'High Risk'), (3, 'Very High Risk'), (4, 'Safe in Moderation')])),
                ('health_effects', models.TextField()),
            ],
        ),
    ]
