# Generated by Django 5.1 on 2024-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
