# Generated by Django 5.1 on 2024-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
